name: 'iridium'
services:
  sync-node:
    build:
      context: .
      dockerfile: ./sync-node/Dockerfile
    working_dir: /app
    environment:
      - NODE_ENV=production
      - NODE_ENV_IRIDIUM_SEED="sync-node 1"
      - APP_HOSTNAME="sync.satellite.dev"
    volumes:
      - ./src:/app/src
      - ./example:/app/example
      - ./sync-node/data:/app/iridium
    ports:
      - '8080:8080'
      - '443:443'
    command: pnpm i && pnpm build && pnpm concurrently "pnpm bootstrap" "pnpm example:sync"
