version: '3'

services:
  sync-node:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.app
    working_dir: /app
    environment:
      # - NODE_ENV=production
      - NODE_ENV_IRIDIUM_SEED=${NODE_ENV_IRIDIUM_SEED}
      - PEERID=${PEERID}
    volumes:
      - ./sync-node/data:/app/iridium
  nginx:
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
      args:
        - SYNC_PREFIX=${SYNC_PREFIX}
        - RELAY_PREFIX=${RELAY_PREFIX}
        - HOSTNAME=${HOSTNAME}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./sync-node/data:/etc/letsencrypt